name: main_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  collection: ^1.18.0
  http_parser: ^4.0.2
  http: ^1.2.2


dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0


flutter:

  assets:
    - assets/gz.png
    - assets/portada.jpg
    - assets/MLB.jpg
    - assets/HATS.jpg
    - assets/invierno.jpg
    - assets/Dodgersws.jpg
    - assets/guantesgk.jpg
    - assets/bate _louisville.jpg
    - assets/casco_rawlings.jpg
    - assets/balonUEFA.jpg
    - assets/dodgershatws.webp
    - assets/liceyshirtblue.jpg
    - assets/gorras/MLB/dodgers.webp
    - assets/gorras/MLB/whiteSox.webp
    - assets/gorras/MLB/detroiU.jpg
    - assets/gorras/MLB/a's.webp
    - assets/gorras/MLB/boston.jpg

    
    

  


  uses-material-design: true

  fonts: 
    - family: Mecha
      fonts:
        - asset: assets/fonts/MechaWar.ttf

    - family: Kenzo
      fonts:
        - asset: assets/fonts/Kenzoestic-Bold.otf
